export const CHECKLISTS_REQUEST = 'CHECKLISTS_REQUEST';
export const CHECKLISTS_SUCCESS = 'CHECKLISTS_SUCCESS';
export const CHECKLISTS_GET_ALL = 'CHECKLISTS_GET_ALL';
export const CHECKLIST_GET_CURRENT = 'CHECKLIST_GET_CURRENT';
export const CHECKLIST_SAVE_CURRENT = 'CHECKLIST_SAVE_CURRENT';
export const CHECKLIST_RESET_CURRENT = 'CHECKLIST_RESET_CURRENT';
export const CHECKLIST_UPLOAD_CURRENT_TO_SERVER = 'CHECKLIST_UPLOAD_CURRENT_TO_SERVER';
