export const ORDERLIST_REQUEST = 'ORDERLIST_REQUEST';
export const ORDERLIST_SUCCESS = 'ORDERLIST_SUCCESS';
export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
