export const PRICES_GET_BY_PRODUCTITEM = 'PRICES_GET_BY_PRODUCTITEM';
export const PRICES_GET_ALL = 'PRICES_GET_ALL';
export const PRICES_GET_STATUS = 'PRICES_GET_STATUS';
export const PRICES_DOWNLOAD_ALL_FROM_SERVER = 'PRICES_DOWNLOAD_ALL_FROM_SERVER';
export const PRICES_SUCCESS = 'PRICES_SUCCESS';
export const PRICES_LOADING = 'PRICES_LOADING';
export const PRICES_ERROR = 'PRICES_ERROR';
export const PRICES_WRITE_ALL_TO_VUEX = 'PRICES_WRITE_ALL_TO_VUEX';
